import { MasterArchetypeRule } from '../types.js';

export const MASTER_ARCHETYPES: MasterArchetypeRule[] = [
  {
    archetype: 'navbar',
    title: 'Navigation Bar / Header',
    description: 'Top-level navigation bar with logo, menu items, hamburger toggle, and search or CTA.',
    preferredTags: ['nav', 'header'],
    rolePatterns: ['navigation', 'banner'],
    keywords: ['menu', 'nav', 'home', 'about', 'services', 'contact', 'sign in', 'log in', 'signup'],
    classPatterns: [/nav/i, /header/i, /navbar/i, /menu/i, /topbar/i, /app-bar/i],
    idPatterns: [/nav/i, /header/i, /navbar/i, /menu/i, /main-nav/i],
    positionBias: 'top',
    maxHeight: 250,
  },
  {
    archetype: 'hero',
    title: 'Hero Section',
    description: 'Prominent introductory section near the top with strong headline, subheadline, CTA button, and hero visual.',
    preferredTags: ['section', 'header', 'div'],
    keywords: ['welcome', 'build', 'create', 'start', 'get started', 'try for free', 'discover', 'the best', 'transform'],
    classPatterns: [/hero/i, /banner/i, /intro/i, /splash/i, /welcome/i, /jumbotron/i, /lead/i],
    idPatterns: [/hero/i, /banner/i, /intro/i, /splash/i],
    positionBias: 'top',
    minHeight: 300,
  },
  {
    archetype: 'features',
    title: 'Features / Capabilities',
    description: 'Showcase of key product features, capabilities, or benefits, often in a grid with icons and headlines.',
    preferredTags: ['section', 'div'],
    keywords: ['features', 'why choose', 'what we do', 'benefits', 'built for', 'speed', 'secure', 'scale', 'platform'],
    classPatterns: [/feature/i, /benefit/i, /service/i, /solution/i, /capability/i, /why-us/i],
    idPatterns: [/feature/i, /benefit/i, /service/i, /solution/i],
    positionBias: 'middle',
  },
  {
    archetype: 'card-grid',
    title: 'Card Grid / Showcase',
    description: 'Repetitive grid or list of cards displaying items, services, articles, or products.',
    preferredTags: ['section', 'div', 'ul'],
    keywords: ['explore', 'products', 'articles', 'projects', 'categories', 'items', 'collection'],
    classPatterns: [/card/i, /grid/i, /showcase/i, /tiles/i, /catalog/i, /portfolio/i],
    idPatterns: [/card/i, /grid/i, /showcase/i, /portfolio/i],
    positionBias: 'middle',
  },
  {
    archetype: 'carousel',
    title: 'Carousel / Slider',
    description: 'Interactive sliding or paging carousel displaying items with navigation dots or prev/next arrows.',
    preferredTags: ['section', 'div'],
    keywords: ['slide', 'prev', 'next', 'carousel', 'swiper', 'glide', 'slick'],
    classPatterns: [/carousel/i, /slider/i, /swiper/i, /slick/i, /glide/i, /slides/i],
    idPatterns: [/carousel/i, /slider/i, /swiper/i, /slick/i],
    positionBias: 'middle',
    interactiveHints: ['swiper-button', 'slick-arrow', 'carousel-control', 'dot', 'arrow-left', 'arrow-right'],
  },
  {
    archetype: 'pricing',
    title: 'Pricing Table / Plans',
    description: 'Pricing comparison table or cards showing tiers, monthly/annual toggles, currency symbols, and feature checklists.',
    preferredTags: ['section', 'div'],
    keywords: ['pricing', 'plan', 'tier', 'per month', '/mo', '/yr', '$', '€', '£', 'free tier', 'pro', 'enterprise', 'billed annually'],
    classPatterns: [/pricing/i, /plans/i, /tier/i, /price/i, /subscription/i],
    idPatterns: [/pricing/i, /plans/i, /price/i],
    positionBias: 'middle',
  },
  {
    archetype: 'testimonials',
    title: 'Testimonials / Reviews',
    description: 'Customer reviews, testimonials, ratings, client quotes, and case studies with avatars and author names.',
    preferredTags: ['section', 'div', 'figure'],
    keywords: ['testimonial', 'reviews', 'what our clients say', 'trusted by', 'customer stories', 'rating', 'stars', 'says'],
    classPatterns: [/testimonial/i, /review/i, /feedback/i, /quote/i, /client/i, /customer-story/i],
    idPatterns: [/testimonial/i, /review/i, /feedback/i, /quotes/i],
    positionBias: 'middle',
  },
  {
    archetype: 'stats',
    title: 'Stats / Milestones / Numbers',
    description: 'Numerical milestones, counters, key metrics, and stats (e.g. 10M+ users, 99.9% uptime).',
    preferredTags: ['section', 'div'],
    keywords: ['satisfied customers', 'downloads', 'uptime', 'accuracy', 'active users', 'countries', 'milestones', '%', 'k+', 'm+'],
    classPatterns: [/stats/i, /counter/i, /metrics/i, /numbers/i, /achievements/i, /facts/i],
    idPatterns: [/stats/i, /counter/i, /metrics/i, /numbers/i],
    positionBias: 'middle',
  },
  {
    archetype: 'faq',
    title: 'FAQ / Accordion',
    description: 'Frequently asked questions with expandable accordion items or question/answer pairs.',
    preferredTags: ['section', 'div'],
    keywords: ['faq', 'frequently asked questions', 'q&a', 'questions', 'answers', 'have questions', 'need help'],
    classPatterns: [/faq/i, /accordion/i, /questions/i, /collapse/i, /toggle/i],
    idPatterns: [/faq/i, /accordion/i, /questions/i],
    positionBias: 'middle',
  },
  {
    archetype: 'cta',
    title: 'Call to Action (CTA)',
    description: 'Focused conversion section urging the user to take action (sign up, download, subscribe, contact sales).',
    preferredTags: ['section', 'div', 'aside'],
    keywords: ['ready to get started', 'join now', 'start your free trial', 'subscribe', 'request a demo', 'sign up today'],
    classPatterns: [/cta/i, /call-to-action/i, /get-started/i, /conversion/i, /newsletter/i, /subscribe/i],
    idPatterns: [/cta/i, /call-to-action/i, /newsletter/i, /subscribe/i],
    positionBias: 'middle',
    maxHeight: 500,
  },
  {
    archetype: 'contact',
    title: 'Contact Form / Location',
    description: 'Contact form with input fields for name, email, message, map embed, and contact details.',
    preferredTags: ['section', 'div', 'form'],
    keywords: ['contact us', 'send message', 'get in touch', 'email us', 'phone', 'location', 'address', 'leave a message'],
    classPatterns: [/contact/i, /inquiry/i, /reach-us/i, /touch/i, /form-container/i],
    idPatterns: [/contact/i, /inquiry/i, /touch/i],
    positionBias: 'bottom',
  },
  {
    archetype: 'gallery',
    title: 'Gallery / Media Showcase',
    description: 'Image or video gallery, portfolio grid, screenshots, or visual media wall.',
    preferredTags: ['section', 'div'],
    keywords: ['gallery', 'portfolio', 'work', 'photos', 'shots', 'screenshots'],
    classPatterns: [/gallery/i, /portfolio/i, /masonry/i, /media-wall/i, /photos/i],
    idPatterns: [/gallery/i, /portfolio/i],
    positionBias: 'middle',
  },
  {
    archetype: 'footer',
    title: 'Footer',
    description: 'Bottom footer containing legal links, copyright notices, sitemaps, privacy policy, and social links.',
    preferredTags: ['footer', 'section', 'div'],
    rolePatterns: ['contentinfo'],
    keywords: ['all rights reserved', 'copyright', 'privacy policy', 'terms of service', 'cookies', 'sitemap', 'legal'],
    classPatterns: [/footer/i, /foot/i, /bottom-bar/i, /subfooter/i, /copyright/i],
    idPatterns: [/footer/i, /foot/i, /copyright/i],
    positionBias: 'bottom',
  },
  {
    archetype: 'content',
    title: 'Generic Content / About Section',
    description: 'Informational section with narrative text, about company info, or mission statement.',
    preferredTags: ['section', 'article', 'div'],
    keywords: ['about us', 'our mission', 'story', 'who we are', 'vision'],
    classPatterns: [/about/i, /story/i, /content/i, /mission/i, /overview/i],
    idPatterns: [/about/i, /story/i, /content/i],
    positionBias: 'middle',
  },
];
